//! tower's verbs as typed tools, the descriptor list an MCP server
//! serves as `tower__<name>`.
//!
//! Every descriptor is generated by walking the clap tree, so a flag
//! added to `cli.rs` is a property here by existing, and the spell-back
//! test parses every verb's descriptor back through clap the way the
//! server will — every verb, not only the served ones, so promoting a
//! verb to a tool is a list edit and never a schema surprise — and drift
//! is a failing test, not a policy. The server spells a call from the
//! schema: positionals first in `positional` order, an array positional
//! as bare items, then every other key as `--key`, `--key <v>`, or the
//! flag repeated for an array, with `--json` appended. Every option
//! therefore needs a long spelling; the short-only `-m` and `-n` carry
//! hidden aliases in `cli.rs` for exactly this.
//!
//! The server adds a `cwd` property of its own, so the schema never
//! closes with `additionalProperties: false`.

// #19's MCP server is the caller; until it lands only the tests read this.
#![allow(dead_code)]

use std::any::TypeId;

use clap::{ArgAction, CommandFactory};
use serde::{Serialize, Serializer};
use serde_json::{Value, json};

use crate::cli::Cli;

/// The clap tree with its built-ins materialized — the `help` subcommand
/// and the auto flags exist to be skipped by name rather than by
/// accident of build order.
pub fn tree() -> clap::Command {
    let mut root = Cli::command();
    root.build();
    root
}

/// A command's verbs: its visible subcommands in clap order, `help`
/// excepted. The tool list and the read-only table both walk this, so
/// the two cannot disagree about what a verb is.
pub fn verbs_of(cmd: &clap::Command) -> impl Iterator<Item = &clap::Command> {
    cmd.get_subcommands()
        .filter(|sub| !sub.is_hide_set() && sub.get_name() != "help")
}

/// Whether a verb only reads. An explicit match over every verb name,
/// `lanes()`'s exhaustive-table discipline: a verb this table has not
/// heard of is `None`, which a descriptor reads as "writes" and a unit
/// test reads as a verb nobody sorted.
pub fn read_only(verb: &str) -> Option<bool> {
    match verb {
        "board" | "brief" | "procedures" | "skills" | "explain" | "version" | "doctor"
        | "briefing" => Some(true),
        "next" | "file" | "comment" | "edit" | "link" | "unlink" | "decompose" | "assign"
        | "status" | "cancel" | "hold" | "answer" | "done" | "config" | "update" | "serve" => {
            Some(false)
        }
        _ => None,
    }
}

/// The verbs served as tools, in clap order: the loop's four gestures
/// — pull, read the brief, stop with a question, finish. fufu's rule
/// for its own seven decides the rest: a verb is a tool only where the
/// shell adds nothing, and an agent with a shell in hand reaches for
/// the shell anyway. Everything a person types, and everything the
/// skills teach as a command line, stays the command line.
pub const TOOLS: &[&str] = &["next", "brief", "hold", "done"];

/// The verbs that are not tools — named, so a new verb has to be sorted
/// into one list or the other.
#[cfg(test)]
const NOT_TOOLS: &[&str] = &[
    "board",
    "file",
    "comment",
    "edit",
    "link",
    "unlink",
    "decompose",
    "procedures",
    "skills",
    "assign",
    "status",
    "cancel",
    "answer",
    "explain",
    "config",
    "version",
    "update",
    "doctor",
    "serve",
    "briefing",
];

#[derive(Serialize)]
pub struct Descriptor {
    pub name: String,
    pub description: String,
    #[serde(rename = "inputSchema")]
    pub input_schema: Schema,
    pub annotations: Annotations,
}

#[derive(Serialize, Default)]
pub struct Schema {
    #[serde(rename = "type")]
    pub kind: &'static str,
    pub properties: Properties,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub required: Vec<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub positional: Vec<String>,
}

#[derive(Serialize)]
pub struct Annotations {
    #[serde(rename = "readOnlyHint")]
    pub read_only_hint: bool,
    #[serde(rename = "destructiveHint")]
    pub destructive_hint: bool,
}

/// The properties in clap order. serde_json's map would sort them; a
/// reader of the server's listing sees the flags the way the help page
/// orders them.
#[derive(Default)]
pub struct Properties(pub Vec<(String, Value)>);

#[cfg(test)]
impl Properties {
    pub fn get(&self, key: &str) -> Option<&Value> {
        self.0.iter().find(|(k, _)| k == key).map(|(_, v)| v)
    }
}

impl Serialize for Properties {
    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.collect_map(self.0.iter().map(|(k, v)| (k, v)))
    }
}

pub fn descriptors() -> Vec<Descriptor> {
    let tree = tree();
    verbs_of(&tree)
        .filter(|sub| TOOLS.contains(&sub.get_name()))
        .map(describe)
        .collect()
}

fn describe(cmd: &clap::Command) -> Descriptor {
    let name = cmd.get_name().to_string();
    Descriptor {
        description: cmd.get_about().map(ToString::to_string).unwrap_or_default(),
        input_schema: schema(cmd),
        annotations: Annotations {
            read_only_hint: read_only(&name).unwrap_or(false),
            destructive_hint: false,
        },
        name,
    }
}

/// One verb's schema: every positional a slot, every option a
/// property, required where clap says so.
fn schema(cmd: &clap::Command) -> Schema {
    let mut schema = Schema {
        kind: "object",
        ..Schema::default()
    };
    for arg in args_of(cmd) {
        let (name, mut value) = property(arg);
        value["description"] = json!(arg.get_help().map(ToString::to_string).unwrap_or_default());
        if arg.is_positional() {
            schema.positional.push(name.clone());
            if arg.is_required_set() {
                schema.required.push(name.clone());
            }
        }
        schema.properties.0.push((name, value));
    }
    schema
}

/// The arguments a caller spells: the globals (`--json`, appended by
/// the server itself) and clap's own `help` are not among them.
fn args_of(cmd: &clap::Command) -> impl Iterator<Item = &clap::Arg> {
    cmd.get_arguments()
        .filter(|arg| !arg.is_global_set() && arg.get_id() != "help")
}

/// The property's key and its type. A positional is keyed by its id;
/// an option by its long, else its one alias — a flag with neither is
/// unspellable, which the unit test refuses.
fn property(arg: &clap::Arg) -> (String, Value) {
    let name = if arg.is_positional() {
        arg.get_id().to_string()
    } else {
        long_of(arg).unwrap_or_else(|| {
            panic!(
                "`{}` has no long spelling for the server to emit",
                arg.get_id()
            )
        })
    };
    (name, kind(arg))
}

fn long_of(arg: &clap::Arg) -> Option<String> {
    arg.get_long()
        .map(ToString::to_string)
        .or_else(|| match arg.get_all_aliases().as_deref() {
            Some([alias]) => Some((*alias).to_string()),
            _ => None,
        })
}

fn kind(arg: &clap::Arg) -> Value {
    match arg.get_action() {
        ArgAction::SetTrue | ArgAction::SetFalse => json!({"type": "boolean"}),
        ArgAction::Append => json!({"type": "array", "items": {"type": "string"}}),
        ArgAction::Count => json!({"type": "integer"}),
        _ if arg.get_value_parser().type_id() == TypeId::of::<usize>() => {
            json!({"type": "integer"})
        }
        _ => json!({"type": "string"}),
    }
}

#[cfg(test)]
mod tests {
    use clap::Parser;

    use super::*;
    use crate::cli::Cli;

    #[test]
    fn every_verb_is_sorted_by_the_read_only_table() {
        let tree = tree();
        let names: Vec<&str> = verbs_of(&tree).map(clap::Command::get_name).collect();
        assert!(names.len() >= 24, "the walk is broken: {names:?}");
        for name in &names {
            assert!(
                read_only(name).is_some(),
                "`{name}` is a verb the read-only table has not sorted"
            );
        }
        // And the table names no verb clap does not have.
        for name in [
            "board",
            "brief",
            "procedures",
            "skills",
            "explain",
            "version",
            "doctor",
            "briefing",
            "next",
            "file",
            "comment",
            "edit",
            "link",
            "unlink",
            "decompose",
            "assign",
            "status",
            "cancel",
            "hold",
            "answer",
            "done",
            "config",
            "update",
            "serve",
        ] {
            assert!(
                names.contains(&name),
                "`{name}` is in the table, not the tree"
            );
        }
    }

    /// A new verb is sorted into `TOOLS` or `NOT_TOOLS`, and both name
    /// only verbs clap has.
    #[test]
    fn every_verb_is_a_tool_or_named_as_not_one() {
        let tree = tree();
        let names: Vec<&str> = verbs_of(&tree).map(clap::Command::get_name).collect();
        for name in &names {
            let sorted = [TOOLS.contains(name), NOT_TOOLS.contains(name)];
            assert_eq!(
                sorted.iter().filter(|b| **b).count(),
                1,
                "`{name}` must be in exactly one of TOOLS and NOT_TOOLS"
            );
        }
        for name in TOOLS.iter().chain(NOT_TOOLS) {
            assert!(names.contains(name), "`{name}` is listed but not a verb");
        }
    }

    /// Every option on every verb has a spelling the server can emit: a
    /// long, or one hidden alias standing in for a short-only flag.
    #[test]
    fn every_option_has_a_long_spelling() {
        let tree = tree();
        let mut checked = 0usize;
        for cmd in verbs_of(&tree) {
            for arg in args_of(cmd).filter(|arg| !arg.is_positional()) {
                assert!(
                    long_of(arg).is_some(),
                    "`{}`: {} has neither a long nor an alias — add `alias = \"…\"`",
                    cmd.get_name(),
                    arg.get_id()
                );
                checked += 1;
            }
        }
        assert!(
            checked >= 20,
            "only {checked} options walked — the walk is broken"
        );
    }

    #[test]
    fn the_descriptors_carry_the_shape_the_server_checks() {
        let all = descriptors();
        let names: Vec<&str> = all.iter().map(|d| d.name.as_str()).collect();
        assert_eq!(names, TOOLS);
        for d in &all {
            assert!(!d.description.trim().is_empty(), "{}", d.name);
            assert_eq!(d.input_schema.kind, "object");
            assert!(
                !(d.annotations.read_only_hint && d.annotations.destructive_hint),
                "{}",
                d.name
            );
            for (key, _) in &d.input_schema.properties.0 {
                assert!(
                    !["json", "help", "cwd"].contains(&key.as_str()),
                    "{}: `{key}` is not the caller's to spell",
                    d.name
                );
            }
        }
        let brief = all.iter().find(|d| d.name == "brief").expect("brief");
        assert!(brief.annotations.read_only_hint);
        assert_eq!(brief.input_schema.positional, ["flight"]);
        assert_eq!(brief.input_schema.required, ["flight"]);
        let hold = all.iter().find(|d| d.name == "hold").expect("hold");
        assert!(!hold.annotations.read_only_hint);
        assert!(hold.input_schema.properties.get("message").is_some());
        let done = all.iter().find(|d| d.name == "done").expect("done");
        assert_eq!(done.input_schema.positional, ["flight"]);
        assert_eq!(done.input_schema.required, ["flight"]);
    }

    /// The generator covers the whole grammar, served or not: the
    /// integer and the boolean, the array positional and the array
    /// option — so a verb promoted to a tool gets a schema that was
    /// already right.
    #[test]
    fn the_generator_covers_the_grammar() {
        let tree = tree();
        let verb = |name: &str| describe(tree.find_subcommand(name).expect(name));
        let next = verb("next");
        assert_eq!(
            next.input_schema.properties.get("count").unwrap()["type"],
            "integer"
        );
        assert_eq!(
            next.input_schema.properties.get("peek").unwrap()["type"],
            "boolean"
        );
        let file = verb("file");
        assert_eq!(file.input_schema.positional, ["first", "second"]);
        assert_eq!(
            file.input_schema.properties.get("label").unwrap()["type"],
            "array"
        );
        assert!(file.input_schema.properties.get("message").is_some());
        assert!(!file.annotations.read_only_hint);
        let decompose = verb("decompose");
        assert_eq!(
            decompose.input_schema.properties.get("parts").unwrap()["type"],
            "array"
        );
        assert!(verb("board").annotations.read_only_hint);
    }

    /// A value as the server would spell it on argv: a string is a word, an
    /// integer a number, an array one bare item.
    fn placeholder(value: &Value) -> &'static str {
        match value["type"].as_str() {
            Some("integer") => "1",
            _ => "x",
        }
    }

    /// One option as the server spells it: the bare flag for a boolean, the
    /// flag repeated for an array, `--key <v>` otherwise.
    fn spell_option(key: &str, value: &Value) -> Vec<String> {
        let flag = format!("--{key}");
        match value["type"].as_str() {
            Some("boolean") => vec![flag],
            Some("array") => vec![flag.clone(), "x".into(), flag, "x".into()],
            _ => vec![flag, placeholder(value).into()],
        }
    }

    fn parse(verb: &str, positionals: &[String], option: &[String]) {
        let mut argv = vec!["atc".to_string(), verb.to_string()];
        argv.extend(positionals.iter().cloned());
        argv.extend(option.iter().cloned());
        argv.push("--json".to_string());
        if let Err(err) = Cli::try_parse_from(&argv) {
            panic!(
                "{}: the server would spell `{}`, which clap refuses:\n{err}",
                verb,
                argv.join(" ")
            );
        }
    }

    /// Every verb's descriptor, spelled the way the server spells a call,
    /// parses back through clap: the positionals alone, then the
    /// positionals with each option in turn — one at a time, because a
    /// caller passing two keys clap declares in conflict is refused on
    /// purpose.
    #[test]
    fn every_descriptor_spells_back_onto_clap() {
        let tree = tree();
        for cmd in verbs_of(&tree) {
            let d = describe(cmd);
            let props = &d.input_schema.properties;
            let positional = &d.input_schema.positional;
            let options: Vec<(&String, &Value)> = props
                .0
                .iter()
                .filter(|(key, _)| !positional.contains(key))
                .map(|(key, value)| (key, value))
                .collect();
            let words: Vec<String> = positional
                .iter()
                .map(|key| placeholder(props.get(key).unwrap()).to_string())
                .collect();
            parse(&d.name, &words, &[]);
            for (key, value) in &options {
                // A positional clap declares in conflict with the option
                // is a refusal on purpose — `config <key> <value>
                // --unset` — so the spelling stops at the first one,
                // the way a caller who read the refusal would.
                let arg = args_of(cmd)
                    .find(|arg| long_of(arg).as_deref() == Some(key.as_str()))
                    .expect("an option is an arg");
                // Clap reads a conflict from the side that declared
                // it, so both sides are asked.
                let conflicts = |a: &clap::Arg, b: &clap::Arg| {
                    cmd.get_arg_conflicts_with(a)
                        .iter()
                        .any(|other| other.get_id() == b.get_id())
                };
                let clear = positional
                    .iter()
                    .position(|key| {
                        let slot = args_of(cmd)
                            .find(|arg| arg.get_id() == key.as_str())
                            .expect("a slot is an arg");
                        conflicts(arg, slot) || conflicts(slot, arg)
                    })
                    .unwrap_or(positional.len());
                parse(&d.name, &words[..clear], &spell_option(key, value));
            }
        }
    }
}
