//! `--ff-tools`: tower's verbs as typed tools, for `ff mcp` to serve as
//! `tower__<name>`.
//!
//! Every descriptor is generated by walking the clap tree, so a flag
//! added to `cli.rs` is a property here by existing, and the spell-back
//! test parses every descriptor back through clap the way fufu will —
//! drift is a failing test, not a policy. fufu spells a call from the
//! schema: positionals first in `positional` order, an array positional
//! as bare items, then every other key as `--key`, `--key <v>`, or the
//! flag repeated for an array, with `--json` appended. Every option
//! therefore needs a long spelling; the short-only `-m` and `-n` carry
//! hidden aliases in `cli.rs` for exactly this.
//!
//! fufu adds a `cwd` property of its own, so the schema never closes with
//! `additionalProperties: false`.

use std::any::TypeId;

use clap::ArgAction;
use serde::{Serialize, Serializer};
use serde_json::{Value, json};

use super::manifest;

/// The verbs served as tools, in clap order. A verb is a tool when an
/// agent has a reason to call it mid-session; the rest — the process,
/// the updater, the introspection verbs, the settings — are a person's
/// or fufu's own.
pub const TOOLS: &[&str] = &[
    "board",
    "next",
    "brief",
    "file",
    "comment",
    "edit",
    "link",
    "unlink",
    "decompose",
    "procedures",
    "skills",
    "assign",
    "status",
    "cancel",
    "hold",
    "answer",
    "done",
    "explain",
    "bay",
];

/// The verbs that are not tools — named, so a new verb has to be sorted
/// into one list or the other.
#[cfg(test)]
const NOT_TOOLS: &[&str] = &["config", "version", "update", "doctor", "serve", "briefing"];

#[derive(Serialize)]
pub struct Descriptor {
    pub name: String,
    pub description: String,
    #[serde(rename = "inputSchema")]
    pub input_schema: Schema,
    pub annotations: Annotations,
}

#[derive(Serialize, Default)]
pub struct Schema {
    #[serde(rename = "type")]
    pub kind: &'static str,
    pub properties: Properties,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub required: Vec<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub positional: Vec<String>,
}

#[derive(Serialize)]
pub struct Annotations {
    #[serde(rename = "readOnlyHint")]
    pub read_only_hint: bool,
    #[serde(rename = "destructiveHint")]
    pub destructive_hint: bool,
}

/// The properties in clap order. serde_json's map would sort them; a
/// reader of `ff mcp`'s listing sees the flags the way the help page
/// orders them.
#[derive(Default)]
pub struct Properties(pub Vec<(String, Value)>);

impl Properties {
    pub fn get(&self, key: &str) -> Option<&Value> {
        self.0.iter().find(|(k, _)| k == key).map(|(_, v)| v)
    }

    fn get_mut(&mut self, key: &str) -> Option<&mut Value> {
        self.0.iter_mut().find(|(k, _)| k == key).map(|(_, v)| v)
    }
}

impl Serialize for Properties {
    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.collect_map(self.0.iter().map(|(k, v)| (k, v)))
    }
}

pub fn descriptors() -> Vec<Descriptor> {
    let tree = super::tree();
    super::verbs_of(&tree)
        .filter(|sub| TOOLS.contains(&sub.get_name()))
        .map(describe)
        .collect()
}

fn describe(cmd: &clap::Command) -> Descriptor {
    let name = cmd.get_name().to_string();
    Descriptor {
        description: cmd.get_about().map(ToString::to_string).unwrap_or_default(),
        input_schema: schema(cmd),
        annotations: Annotations {
            read_only_hint: manifest::read_only(&name).unwrap_or(false),
            destructive_hint: false,
        },
        name,
    }
}

/// One verb's schema. A verb with sub-verbs — `bay` — takes them as an
/// `action` enum, first positional and required, and the sub-verbs'
/// own arguments merge in after it: positionals by index, options by
/// name, each slot named by the first sub-verb declaring it and
/// described by every one that does.
fn schema(cmd: &clap::Command) -> Schema {
    let mut schema = Schema {
        kind: "object",
        ..Schema::default()
    };
    let subs: Vec<&clap::Command> = super::verbs_of(cmd).collect();
    if !subs.is_empty() {
        let names: Vec<&str> = subs.iter().map(|sub| sub.get_name()).collect();
        schema.properties.0.push((
            "action".to_string(),
            json!({
                "type": "string",
                "enum": names,
                "description": format!("The {} action: {}.", cmd.get_name(), names.join(", ")),
            }),
        ));
        schema.required.push("action".to_string());
        schema.positional.push("action".to_string());
    }
    walk(cmd, None, &mut schema);
    let base = schema.positional.len();
    for sub in subs {
        walk_merged(sub, base, &mut schema);
    }
    schema
}

/// The verb's own arguments: every positional a slot, every option a
/// property, required where clap says so.
fn walk(cmd: &clap::Command, prefix: Option<&str>, schema: &mut Schema) {
    for arg in args_of(cmd) {
        let (name, mut value) = property(arg);
        value["description"] = json!(describe_arg(arg, prefix));
        if arg.is_positional() {
            schema.positional.push(name.clone());
            if arg.is_required_set() {
                schema.required.push(name.clone());
            }
        }
        schema.properties.0.push((name, value));
    }
}

/// A sub-verb's arguments folded into the parent's schema. Nothing a
/// sub-verb declares is required at the union level: the other actions
/// do not take it.
fn walk_merged(sub: &clap::Command, base: usize, schema: &mut Schema) {
    let prefix = sub.get_name();
    let mut slot = base;
    for arg in args_of(sub) {
        let (name, mut value) = property(arg);
        let help = describe_arg(arg, Some(prefix));
        let existing = if arg.is_positional() {
            let existing = schema.positional.get(slot).cloned();
            slot += 1;
            existing
        } else {
            schema.properties.get(&name).map(|_| name.clone())
        };
        match existing {
            Some(key) => {
                let value = schema
                    .properties
                    .get_mut(&key)
                    .expect("a slot is a property");
                let joined = format!(
                    "{}; {help}",
                    value["description"].as_str().unwrap_or_default()
                );
                value["description"] = json!(joined);
            }
            None => {
                value["description"] = json!(help);
                if arg.is_positional() {
                    schema.positional.push(name.clone());
                }
                schema.properties.0.push((name, value));
            }
        }
    }
}

/// The arguments a caller spells: the globals (`--json`, appended by
/// fufu itself) and clap's own `help` are not among them.
fn args_of(cmd: &clap::Command) -> impl Iterator<Item = &clap::Arg> {
    cmd.get_arguments()
        .filter(|arg| !arg.is_global_set() && arg.get_id() != "help")
}

/// The property's key and its type. A positional is keyed by its id;
/// an option by its long, else its one alias — a flag with neither is
/// unspellable, which the unit test refuses.
fn property(arg: &clap::Arg) -> (String, Value) {
    let name = if arg.is_positional() {
        arg.get_id().to_string()
    } else {
        long_of(arg)
            .unwrap_or_else(|| panic!("`{}` has no long spelling for fufu to emit", arg.get_id()))
    };
    (name, kind(arg))
}

fn long_of(arg: &clap::Arg) -> Option<String> {
    arg.get_long()
        .map(ToString::to_string)
        .or_else(|| match arg.get_all_aliases().as_deref() {
            Some([alias]) => Some((*alias).to_string()),
            _ => None,
        })
}

fn kind(arg: &clap::Arg) -> Value {
    match arg.get_action() {
        ArgAction::SetTrue | ArgAction::SetFalse => json!({"type": "boolean"}),
        ArgAction::Append => json!({"type": "array", "items": {"type": "string"}}),
        ArgAction::Count => json!({"type": "integer"}),
        _ if arg.get_value_parser().type_id() == TypeId::of::<usize>() => {
            json!({"type": "integer"})
        }
        _ => json!({"type": "string"}),
    }
}

fn describe_arg(arg: &clap::Arg, prefix: Option<&str>) -> String {
    let help = arg.get_help().map(ToString::to_string).unwrap_or_default();
    match prefix {
        Some(prefix) => format!("{prefix}: {help}"),
        None => help,
    }
}

#[cfg(test)]
mod tests {
    use clap::Parser;

    use super::*;
    use crate::cli::Cli;

    /// A new verb is sorted into `TOOLS` or `NOT_TOOLS`, and both name
    /// only verbs clap has.
    #[test]
    fn every_verb_is_a_tool_or_named_as_not_one() {
        let tree = super::super::tree();
        let names: Vec<&str> = super::super::verbs_of(&tree)
            .map(clap::Command::get_name)
            .collect();
        for name in &names {
            let sorted = [TOOLS.contains(name), NOT_TOOLS.contains(name)];
            assert_eq!(
                sorted.iter().filter(|b| **b).count(),
                1,
                "`{name}` must be in exactly one of TOOLS and NOT_TOOLS"
            );
        }
        for name in TOOLS.iter().chain(NOT_TOOLS) {
            assert!(names.contains(name), "`{name}` is listed but not a verb");
        }
    }

    /// Every option on every tool has a spelling fufu can emit: a long,
    /// or one hidden alias standing in for a short-only flag.
    #[test]
    fn every_option_has_a_long_spelling() {
        let tree = super::super::tree();
        let mut checked = 0usize;
        for verb in super::super::verbs_of(&tree).filter(|sub| TOOLS.contains(&sub.get_name())) {
            for cmd in std::iter::once(verb).chain(super::super::verbs_of(verb)) {
                for arg in args_of(cmd).filter(|arg| !arg.is_positional()) {
                    assert!(
                        long_of(arg).is_some(),
                        "`{} {}`: {} has neither a long nor an alias — add `alias = \"…\"`",
                        verb.get_name(),
                        cmd.get_name(),
                        arg.get_id()
                    );
                    checked += 1;
                }
            }
        }
        assert!(
            checked >= 20,
            "only {checked} options walked — the walk is broken"
        );
    }

    #[test]
    fn the_descriptors_carry_the_shape_fufu_checks() {
        let all = descriptors();
        let names: Vec<&str> = all.iter().map(|d| d.name.as_str()).collect();
        assert_eq!(names, TOOLS);
        for d in &all {
            assert!(!d.description.trim().is_empty(), "{}", d.name);
            assert_eq!(d.input_schema.kind, "object");
            assert!(
                !(d.annotations.read_only_hint && d.annotations.destructive_hint),
                "{}",
                d.name
            );
            for (key, _) in &d.input_schema.properties.0 {
                assert!(
                    !["json", "help", "cwd"].contains(&key.as_str()),
                    "{}: `{key}` is not the caller's to spell",
                    d.name
                );
            }
        }
        let bay = all.iter().find(|d| d.name == "bay").expect("bay");
        assert_eq!(bay.input_schema.positional, ["action", "path", "branch"]);
        assert_eq!(bay.input_schema.required, ["action"]);
        assert_eq!(
            bay.input_schema.properties.get("action").unwrap()["enum"],
            json!(["list", "warm", "release"])
        );
        let path = bay.input_schema.properties.get("path").unwrap();
        let description = path["description"].as_str().unwrap();
        assert!(
            description.starts_with("warm: ") && description.contains("; release: "),
            "{description}"
        );
        let next = all.iter().find(|d| d.name == "next").expect("next");
        assert_eq!(
            next.input_schema.properties.get("count").unwrap()["type"],
            "integer"
        );
        assert_eq!(
            next.input_schema.properties.get("peek").unwrap()["type"],
            "boolean"
        );
        let file = all.iter().find(|d| d.name == "file").expect("file");
        assert_eq!(file.input_schema.positional, ["first", "second"]);
        assert_eq!(
            file.input_schema.properties.get("label").unwrap()["type"],
            "array"
        );
        assert!(file.input_schema.properties.get("message").is_some());
        assert!(!file.annotations.read_only_hint);
        let board = all.iter().find(|d| d.name == "board").expect("board");
        assert!(board.annotations.read_only_hint);
    }

    /// A value as fufu would spell it on argv: a string is a word, an
    /// integer a number, an array one bare item.
    fn placeholder(value: &Value) -> &'static str {
        match value["type"].as_str() {
            Some("integer") => "1",
            _ => "x",
        }
    }

    /// One option as fufu spells it: the bare flag for a boolean, the
    /// flag repeated for an array, `--key <v>` otherwise.
    fn spell_option(key: &str, value: &Value) -> Vec<String> {
        let flag = format!("--{key}");
        match value["type"].as_str() {
            Some("boolean") => vec![flag],
            Some("array") => vec![flag.clone(), "x".into(), flag, "x".into()],
            _ => vec![flag, placeholder(value).into()],
        }
    }

    fn parse(verb: &str, positionals: &[String], option: &[String]) {
        let mut argv = vec!["ff-tower".to_string(), verb.to_string()];
        argv.extend(positionals.iter().cloned());
        argv.extend(option.iter().cloned());
        argv.push("--json".to_string());
        if let Err(err) = Cli::try_parse_from(&argv) {
            panic!(
                "{}: fufu would spell `{}`, which clap refuses:\n{err}",
                verb,
                argv.join(" ")
            );
        }
    }

    /// Every descriptor, spelled the way fufu spells a call, parses back
    /// through clap: the positionals alone, then the positionals with
    /// each option in turn — one at a time, because a caller passing two
    /// keys clap declares in conflict is refused on purpose.
    #[test]
    fn every_descriptor_spells_back_onto_clap() {
        let tree = super::super::tree();
        for d in descriptors() {
            let cmd = tree.find_subcommand(&d.name).expect("a verb");
            let props = &d.input_schema.properties;
            let positional = &d.input_schema.positional;
            let options: Vec<(&String, &Value)> = props
                .0
                .iter()
                .filter(|(key, _)| !positional.contains(key))
                .map(|(key, value)| (key, value))
                .collect();
            let subs: Vec<&clap::Command> = super::super::verbs_of(cmd).collect();
            if subs.is_empty() {
                let words: Vec<String> = positional
                    .iter()
                    .map(|key| placeholder(props.get(key).unwrap()).to_string())
                    .collect();
                parse(&d.name, &words, &[]);
                for (key, value) in &options {
                    parse(&d.name, &words, &spell_option(key, value));
                }
                continue;
            }
            assert_eq!(positional.first().map(String::as_str), Some("action"));
            for sub in subs {
                // The sub-verb's own slots, and no more: the union's other
                // slots belong to its siblings.
                let own = args_of(sub).filter(|arg| arg.is_positional()).count();
                let mut words = vec![sub.get_name().to_string()];
                words.extend(
                    positional[1..1 + own]
                        .iter()
                        .map(|key| placeholder(props.get(key).unwrap()).to_string()),
                );
                parse(&d.name, &words, &[]);
                let declared: Vec<String> = args_of(cmd)
                    .chain(args_of(sub))
                    .filter(|arg| !arg.is_positional())
                    .filter_map(long_of)
                    .collect();
                for (key, value) in &options {
                    if declared.contains(key) {
                        parse(&d.name, &words, &spell_option(key, value));
                    }
                }
            }
        }
    }
}
